function rev_fig6_r2_comparison()
% REV_FIG6_R2_COMPARISON  Reproduce Figure 6: R² comparison across continuous outcomes.
%
% Grouped bar chart (blue = tract-based, yellow = classic) for T1, MTR, FA, MD.
% Black horizontal lines show R² from matched-sample analysis (controls excluded
% so that tract-based and classic models share the same N per metric).
% Three subplots (one per clinical outcome) arranged horizontally in one figure.
%
% Data sources (both in the MS100 root directory):
%   paper_multi_corrected.xlsx      — R² values from the full-sample analysis
%                                     (controls retained for continuous outcomes;
%                                     generated by paper_multi_continuous_ridge_all.m
%                                     with default demographics = {Age, Gender}).
%
%   paper_multi_corrected_sameN.xlsx — R² values re-computed after excluding healthy
%                                     controls so that tract-based and classic models
%                                     are fitted on the exact same subjects per metric
%                                     (same pipeline, controls removed manually before
%                                     running; original code no longer available as a
%                                     separate script — the exclusion was done ad hoc).
%
% Usage:
%   rev_fig6_r2_comparison

    clc; close all;

    %% ── Paths ─────────────────────────────────────────────────────────────
    script_dir = fileparts(mfilename('fullpath'));
    sheet      = 'Continuous_Models';

    full_file  = fullfile(script_dir, 'outputs', 'paper_multi_corrected.xlsx');
    sameN_file = fullfile(script_dir, 'outputs', 'paper_multi_corrected_sameN.xlsx');

    assert(isfile(full_file),  'Missing: %s', full_file);
    assert(isfile(sameN_file), 'Missing: %s', sameN_file);

    %% ── Config ─────────────────────────────────────────────────────────────
    metrics_to_show  = {'T1','MTR','FA','MD'};   % Lnorm excluded
    clinical_labels  = {'T25FW', '9HPT-D', '9HPT-ND'};
    clinical_keys    = {'T25FW', 'x9HPTD', 'x9HPTND'};

    color_tract   = [73  167 246] / 255;   % blue
    color_classic = [255 199 119] / 255;   % yellow

    %% ── Load data ──────────────────────────────────────────────────────────
    T_full  = readtable(full_file,  'Sheet', sheet);
    T_sameN = readtable(sameN_file, 'Sheet', sheet);

    %% ── Parse tables ───────────────────────────────────────────────────────
    % ClinicalMetric column: 'T25FW-T1', 'x9HPTD-MTR', etc.
    D_full  = parse_table(T_full);
    D_sameN = parse_table(T_sameN);

    %% ── Plot ───────────────────────────────────────────────────────────────
    fig = figure('Position', [100 100 1100 360], 'Color', 'white');

    for ci = 1:numel(clinical_keys)
        ckey   = clinical_keys{ci};
        clabel = clinical_labels{ci};

        % Collect per-metric R² and N for this clinical measure
        r2_tract   = nan(1, numel(metrics_to_show));
        r2_classic = nan(1, numel(metrics_to_show));
        n_tract    = nan(1, numel(metrics_to_show));
        n_classic  = nan(1, numel(metrics_to_show));
        r2_tract_sN   = nan(1, numel(metrics_to_show));
        r2_classic_sN = nan(1, numel(metrics_to_show));

        for mi = 1:numel(metrics_to_show)
            metric = metrics_to_show{mi};
            key    = sprintf('%s-%s', ckey, metric);

            row_t = find(strcmp(D_full.key, key) & strcmp(D_full.model, 'tract-based'));
            row_c = find(strcmp(D_full.key, key) & strcmp(D_full.model, 'classic'));
            if ~isempty(row_t)
                r2_tract(mi) = D_full.R2(row_t(1));
                n_tract(mi)  = D_full.N(row_t(1));
            end
            if ~isempty(row_c)
                r2_classic(mi) = D_full.R2(row_c(1));
                n_classic(mi)  = D_full.N(row_c(1));
            end

            row_ts = find(strcmp(D_sameN.key, key) & strcmp(D_sameN.model, 'tract-based'));
            row_cs = find(strcmp(D_sameN.key, key) & strcmp(D_sameN.model, 'classic'));
            if ~isempty(row_ts), r2_tract_sN(mi)   = D_sameN.R2(row_ts(1)); end
            if ~isempty(row_cs), r2_classic_sN(mi) = D_sameN.R2(row_cs(1)); end
        end

        subplot(1, 3, ci);
        hold on;

        bar_data = [r2_tract(:), r2_classic(:)];
        b = bar(bar_data, 'grouped');
        b(1).FaceColor = color_tract;
        b(2).FaceColor = color_classic;
        b(1).EdgeColor = 'none';
        b(2).EdgeColor = 'none';

        % --- Sample-size labels above bars ---
        nMetrics = numel(metrics_to_show);
        nGroups  = 2;
        groupWidth = min(0.8, nGroups / (nGroups + 1.5));
        bar_w = groupWidth / nGroups;

        for mi = 1:nMetrics
            x_t = mi - groupWidth/2 + (0.5) * bar_w;
            x_c = mi - groupWidth/2 + (1.5) * bar_w;
            top_t = r2_tract(mi);
            top_c = r2_classic(mi);

            if ~isnan(top_t) && ~isnan(n_tract(mi))
                text(x_t, top_t + 0.008, sprintf('%d', n_tract(mi)), ...
                    'HorizontalAlignment','center', 'FontSize', 8, 'Color','k');
            end
            if ~isnan(top_c) && ~isnan(n_classic(mi))
                text(x_c, top_c + 0.008, sprintf('%d', n_classic(mi)), ...
                    'HorizontalAlignment','center', 'FontSize', 8, 'Color','k');
            end
        end

        % --- Black horizontal lines for same-N R² ---
        for mi = 1:nMetrics
            x_t = mi - groupWidth/2 + (0.5) * bar_w;
            x_c = mi - groupWidth/2 + (1.5) * bar_w;
            hw  = bar_w * 0.4;   % half-width of the line

            if ~isnan(r2_tract_sN(mi))
                plot([x_t - hw, x_t + hw], [r2_tract_sN(mi), r2_tract_sN(mi)], ...
                    'k-', 'LineWidth', 2);
            end
            if ~isnan(r2_classic_sN(mi))
                plot([x_c - hw, x_c + hw], [r2_classic_sN(mi), r2_classic_sN(mi)], ...
                    'k-', 'LineWidth', 2);
            end
        end

        hold off;
        box on; grid off;
        set(gca, 'LineWidth', 1.2, 'FontSize', 11, 'TickDir', 'out');
        xticks(1:nMetrics);
        xticklabels(metrics_to_show);
        xtickangle(0);
        ylabel('R^2', 'FontSize', 12, 'FontWeight', 'bold');
        title(clabel, 'FontSize', 13, 'FontWeight', 'bold');
        ylim([0, 0.55]);

        if ci == 1
            legend({'Tract-based', 'Classic', 'Matched N'}, ...
                'Location', 'northwest', 'FontSize', 9, 'Box', 'off');
        end
    end

    sgtitle('R² Comparison: Tract-based vs Classic (without demographics)', ...
        'FontSize', 13, 'FontWeight', 'bold');

    out_png = fullfile(script_dir, 'rev_fig6_r2_comparison.png');
    saveas(fig, out_png);
    fprintf('Figure saved to: %s\n', out_png);
end


%% ── Helper ──────────────────────────────────────────────────────────────────

function D = parse_table(T)
% Parse the long-format Continuous_Models sheet into a struct with fields:
%   key   — 'ClinicalMeasure-Metric' string (e.g. 'T25FW-T1')
%   model — 'tract-based' or 'classic'
%   N     — sample size (numeric)
%   R2    — R² without demographics (numeric)

    % Identify columns by name (case-insensitive)
    vn    = T.Properties.VariableNames;
    vnl   = lower(vn);
    col   = @(c) vn{strcmp(vnl, lower(c))};

    key_col   = col('ClinicalMetric');
    model_col = col('Model');
    n_col     = col('N');
    r2_col    = col('R2');

    D.key   = string(T.(key_col));
    D.model = lower(strtrim(string(T.(model_col))));
    D.N     = to_num(T.(n_col));
    D.R2    = to_num(T.(r2_col));
end

function v = to_num(v)
    if isnumeric(v), v = double(v); return; end
    if iscell(v),    v = string(v); end
    if isstring(v),  v = str2double(v); return; end
    v = double(v);
end
